platform :ios, '13.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'PharmAI' do
  config = use_native_modules!

  # ✅ Use your local Boost
  pod 'boost', :path => '../boost_1_76_0'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false
  )

  target 'PharmAITests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end